{% set name = "pypif" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f426a4f58157b44727a2fdbe821000d98b5a64951b9ebe8a300d38db7804eefd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - six

test:
  imports:
    - pypif

about:
  home: http://github.com/CitrineInformatics/pypif
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python toolkit for working with PIFs

  description: |
    Python toolkit for working with PIFs
  doc_url: http://citrineinformatics.github.io/pypif
  dev_url: https://github.com/CitrineInformatics/pypif

extra:
  recipe-maintainers:
    - eddotman
    - maxhutch
    - sparadiso
    - jsomara
