travis:
  secure:
    BINSTAR_TOKEN: ZESrGMNhUmzJxl/CV3xr6QittC/KnOtI7rfWc2leGWTW+1uolcOZl2yRi/LO5GPWdo0u02YdptLUCQgy7wLlM/kBhFJvinDmyQxsJcJeGMN+QaTSOIatJu/c2TmVdUcx6ghZ/yNNsTvOA4+M05gXy2ESyfh8Yi/NI20QhjdgtdIBbBb8KlmZG2YSA6GoPy6JypmRO92B7xJaNWN7WMGQiOWhZ3BwiZItOeOcfYCCrjNYiJDCNv5QKsRguDQjwYxh+mGwUaIkBiZ85TaVgHrQRCCU53mdCf/3lObzDeFDMTGYf871ru/P9fr4GQFMGwqp3/Dz8d6LtKq9Rr/Ud8EHZjAReP951nkyPNfuS5e4XQi8ZZQYpY3wi6RYjpzxxXo4UZbm3DI4Pzn7b6lOoZIWwoA+iAYgz/J3ItNElxHRlcNb3wZR5UOAK+IcYM3CBZlMREMgAc5yLFbPzelpYxbxRxpq5hwRwcevB4RtD6XaZUGFrAumkCKuAU9Bw0zrRRvRExVWEz5Cv7CfoROg8etnjVIFICiXdUE+erRzYiNBZJDaIVEHRF7ZAzNRFUWg4ZZSfNizIQM+kcbuyNovfAQzmSfTN5re5TURSlpqqK25BG02AQTV7J7NZJidFyEqXAqgjFCcuwIOJMWDHE4jYThgroL9aixm2accGQw+FT70ZLU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
